-include scripts/Makefile.compiler

# 得到所有的头文件参数
CFLAGS += $(patsubst %, -I%, $(INCLUDE_PATH))

obj-y += $(addprefix example/$(BUILD_DIR)/, $(example-y))

%.o: %.c
	$(CC) -c $(CFLAGS) $< -o $@
# 编译cpp文件
%.o: %.cpp
	$(CXX) -c $(CXXFLAGS) $< -o $@
# 编译汇编文件
%.o: %.s
	$(AS) -c $(ASFLAGS) $< -o $@